Add Arch Linux
LukeShortCloud/container-lukeshortcloud-dev pull request #13
Opened 2024-08-22 11:22 UTC by GuestSneezeOSDev

2024-08-22 14:22 UTC, LukeShortCloud commented
Super cool! I've always thought about making an Arch Linux container but never got around to it. I'll test out this PR later today.

2024-08-23 18:43 UTC, LukeShortCloud commented on Containerfile.archlinux
> +ENV CMD_UPDATE_INSTALL="pacman -Syu"
The command here should be a `pacman -S --needed --noconfirm` instead of a system update.

2024-08-23 18:45 UTC, LukeShortCloud commented on Containerfile.archlinux
> +ENV CMD_UPDATE_INSTALL="pacman -Syu"
The variable should also be called `${CMD_PACMAN_INSTALL}`

2024-08-23 18:45 UTC, LukeShortCloud commented on Containerfile.archlinux
> +RUN ${CMD_UPDATE_INSTALL} && pacman -S base-devel git sudo bash vim nano emacs rsync cpio grub systemd man-db
Here is where you want to run `pacman -Syu`. That should be one `RUN` instruction and then the installation of packages should be a separate `RUN`.

The installation should also use the `${CMD_PACMAN_INSTALL}` variable.

2024-08-23 18:46 UTC, LukeShortCloud commented on Containerfile.archlinux
> +RUN ${CMD_DNF_INSTALL} curl iproute iputils netcat nmap openssh-clients openssl wget
`${CMD_DNF_INSTALL}` should be `${CMD_PACMAN_INSTALL}`

2024-08-23 18:46 UTC, LukeShortCloud commented on Containerfile.archlinux
> +RUN ${CMD_DNF_INSTALL} bash bash-completion bc bzip2 curl findutils glibc-all-langpacks glibc-locale-source gnupg2 gnupg2-smime hostname iproute iputils keyutils man-db man-pages passwd time tree unz
`${CMD_DNF_INSTALL}` should be `${CMD_PACMAN_INSTALL}`

2024-08-23 18:46 UTC, LukeShortCloud commented on Containerfile.archlinux
> +RUN ${CMD_DNF_INSTALL} azure-cli
`${CMD_DNF_INSTALL}` should be `${CMD_PACMAN_INSTALL}`

2024-08-23 18:47 UTC, LukeShortCloud commented on Containerfile.archlinux
> +RUN ls /var/cache/pacman/pkg/ | less
You can remove the `less` here. It might stop the build. `ls` will already show everything in the directory.

2024-08-23 18:47 UTC, LukeShortCloud commented on Containerfile.archlinux
> +RUN pacman -S pacman-contrib
This should use `${CMD_PACMAN_INSTALL}`.

We also want to install packages before the "Cleanup" section begins.

2024-08-23 18:57 UTC, LukeShortCloud commented
For testing purposes to find errors, I'm running this command:

```
sudo docker build --pull --tag lukeshortcloud/dev-archlinux:latest . -f Containerfile.archlinux
```

2024-08-24 10:35 UTC, GuestSneezeOSDev commented
@LukeShortCloud Have you tried building it with `podman`?

2024-08-27 01:01 UTC, LukeShortCloud requested changes
The results when running `sudo docker build` and `podman build` are the same. We're getting closer to this working! I left some comments about most of the major issues.

2024-08-27 01:01 UTC, LukeShortCloud commented on Containerfile.archlinux
> +
I tried a build and even the `archlinux:latest` container needed an update. We need to add these lines here:

```
RUN pacman -S -y
RUN pacman -S -u --noconfirm
```

2024-08-27 01:01 UTC, LukeShortCloud commented on Containerfile.archlinux
> +RUN ${CMD_pacman_INSTALL} && pacman -S base-devel git sudo bash vim nano emacs rsync cpio grub systemd man-db
This fails because no argument is given to the first installation command. Try changing this line to:

```
RUN ${CMD_pacman_INSTALL} base-devel git sudo bash vim nano emacs rsync cpio grub systemd man-db
```

2024-08-27 01:01 UTC, LukeShortCloud commented on Containerfile.archlinux
> +RUN ${CMD_pacman_INSTALL} gzip unzip zip zstd xz-utils unrar
In Arch Linux, the `xz-utils` package is simply called `xz`.

2024-08-27 01:01 UTC, LukeShortCloud commented on Containerfile.archlinux
> +RUN ${CMD_pacman_INSTALL} curl iproute iputils netcat nmap openssh-clients openssl wget
In Arch Linux, the `openssh-clients` (and `openssh-server`) packages are in a single package called `openssh`.

2024-08-27 01:01 UTC, LukeShortCloud commented on Containerfile.archlinux
> +RUN ${CMD_pacman_INSTALL} git git-review gcc golang java jre-openjdk | grep jre | grep jdk
A few issues here:

- `git-review` is only available from the AUR. We can remove this for now.
- In Arch Linux, the `golang` package is simply called `go`.
- Remove the `| grep jre | grep jdk` at the end as they are needed and cause this `RUN` instruction to fail.

2024-09-01 13:32 UTC, closed without merging